// src/pages/Home.tsx
import React from 'react';

const Home: React.FC = () => {
  const BASE = import.meta.env.BASE_URL;

  return (
    <>
      <section style={{ textAlign: 'center', padding: '4rem 0' }}>
        <h1>Image-guided 360-degree Scene Generation with Structural and Visual Consistency</h1>
        <p>
          Y. Katayama,&nbsp;R. Togo,&nbsp;K. Maeda,&nbsp;T. Ogawa,&nbsp;and&nbsp;M. Haseyama
        </p>
        <div>
          {/* <a className="btn" href="#paper">Paper</a>
          <a className="btn" href="#arXiv">arXiv</a>
          <a className="btn" href="#code">Code</a> */}
        </div>

      </section>

      <section id="abstract" style={{ padding: '2rem 1rem' }}>
        <h2>Abstract</h2>
        <p>
          Scene generation is advancing rapidly, opening up new possibilities for virtual-world construction.
          This technology produces continuous 3D scenes and virtual environments from a single image along with textual descriptions.
          However, it remains challenging to maintain structural and visual consistency in text-driven scene generation, where sequential views are synthesized from a single input image.
          To address these inconsistencies, we propose a novel scene generation method based on (i) the use of multiple checkpoint images generated by a Native Multimodal Model (NMM), and (ii) rotation-aware frame interpolation.
          Assuming a fixed camera position with a 360° rotational view, we realize a scene generation that can preserve both structural and visual consistency across views.
          Experimental results demonstrate that our method achieves superior spatial-structural coherence and visual semantic consistency compared to existing approaches.
        </p>
        <div 
        style={{
            display: 'flex', justifyContent: 'center', marginTop: '1rem' 
          }}>
          <video
            src={`${BASE}videos/french_manor.mp4`}
            controls
            style={{ display: 'block', width: '50%', height: 'auto' }}
          >
            Your browser does not support the <code>video</code> element.
          </video>
        </div>  
      </section>

      <section id="method" style={{ padding: '2rem 1rem' }}>
        <h2>Image-guided 360-degree Scene Generation</h2>
        <p>An overview of the overall framework is shown in the below.</p>
        <img
          src={`${BASE}images/overview.svg`}
          alt="Method overview"
          style={{ width: '100%', margin: '1rem 0' }}
        />
        <p>
          We propose an image-guided framework for 360-degree scene generation. 
          Our method extends conventional text-driven approaches by incorporating image-based control.
          Specifically, we employ GPT-4o as a Native Multimodal Model (NMM) and utilize its built-in 4o image generation mechanism to generate multiple novel-viewpoint images from a single input.
          These generated images, along with the original input image, serve as checkpoints for view interpolation. 
          By interpolating between these checkpoints, our approach ensures spatial-structural coherence and visual semantic consistency throughout the 360-degree scene.
        </p>
      </section>

      <section id="comparison" style={{ textAlign: 'center', padding: '2rem 1rem' }}>
        <h2>Comparison with WonderJourney in Video</h2>

        <div style={{ display: 'inline-block', position: 'relative', maxWidth: '100%' }}>
          <video
            src={`${BASE}videos/french_manor_with_border.mp4`}
            controls
            style={{ display: 'block', width: '100%', height: 'auto' }}
          >
            Your browser does not support the <code>video</code> element.
          </video>

          <div
            style={{
              position: 'absolute',
              bottom: '-2.5rem',
              left: 0,
              width: '100%',
              display: 'flex',
            }}
          >
            <div style={{ width: '50%', textAlign: 'center', fontWeight: 'bold', fontSize: '1.5rem' }}>
              Ours
            </div>
            <div style={{ width: '50%', textAlign: 'center', fontWeight: 'bold', fontSize: '1.5rem' }}>
              WJ
            </div>
          </div>
        </div>
      </section>

      <section id="experimental-results" style={{ padding: '2rem 1rem' }}>
        <h2>Experimental Results</h2>
        <img
          src={`${BASE}images/experimental_results.svg`}
          alt="Experimental results overview"
          style={{ width: '100%', margin: '1rem 0' }}
        />
        <p>
          Figures above compare the visual outputs produced by our method and WJ at various viewpoints.
          The fact that the first and last frames are identical demonstrates that our method explicitly accounts for spatial-structural coherence, in contrast to WJ.
          In terms of visual consistency, WJ reveals inconsistency in both texture and style, particularly across widely spaced viewpoints.
          In contrast, our method ensures visual consistency throughout the entire scene, allowing for an immersive experience.
        </p>
      </section>

      <section id="comparison" style={{ textAlign: 'center', padding: '2rem 1rem' }}>
        <h2>More Examples</h2>

        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1rem' }}>
          <div style={{ width: '50%', textAlign: 'center', fontWeight: 'bold', fontSize: '1.5rem' }}>
            Ours
          </div>
          <div style={{ width: '50%', textAlign: 'center', fontWeight: 'bold', fontSize: '1.5rem' }}>
            WJ
          </div>
        </div>
        <div style={{ marginTop: '2rem' }}>
            <video
              src={`${BASE}videos/cyberpunk_2_with_border.mp4`}
              controls
              style={{ width: '100%', height: 'auto' }}
            >
              Your browser does not support the <code>video</code> element.
            </video>
          </div>
          <div style={{ width: '100%', padding: '0' }}>
            <video
              src={`${BASE}videos/real_westlake_with_border.mp4`}
              controls
              style={{ width: '100%', height: 'auto' }}
            >
              Your browser does not support the <code>video</code> element.
            </video>
          <video
            src={`${BASE}videos/ukiyoe_2_with_border.mp4`}
            controls
            style={{ display: 'block', width: '100%', height: 'auto', marginBottom: '1rem' }}
          >
            Your browser does not support the <code>video</code> element.
          </video>
          <video
            src={`${BASE}videos/real_campus_with_border.mp4`}
            controls
            style={{ display: 'block', width: '100%', height: 'auto' }}
          >
            Your browser does not support the <code>video</code> element.
          </video>
        </div>
      </section>

    </>
  );
};

export default Home;
