// src/pages/Home.tsx
import React, { useState } from 'react';
import Gallery from '../components/Gallery';
import VideoCompare from '../components/VideoCompare';

const Home: React.FC = () => {
  const BASE = import.meta.env.BASE_URL;
  const videoItems = [
    {
      thumbnail:`${BASE}videos/sample_video.mp4`,
      src:      `${BASE}videos/sample_video.mp4`,
      video:     true,
      videoSrc: `${BASE}videos/sample_video.mp4`,
    }
  ];

  const videoPairs = [
    {
      otherSrc: `${BASE}videos/french_manor_WJ.mp4`,
      oursSrc:  `${BASE}videos/output_french_manor_2.mp4`,
      otherLabel: 'WonderJourney',
      oursLabel:  'Ours',
    },
    {
      otherSrc: `${BASE}videos/output_cyberpunk_2_WJ.mp4`,
      oursSrc:  `${BASE}videos/output_cyberpunk_2.mp4`,
      otherLabel: 'WonderJourney',
      oursLabel:  'Ours',
    }
  ];

  const [current, setCurrent] = useState(0);
  const pairCount = videoPairs.length;

  const handlePrev = () =>
    setCurrent((current + pairCount - 1) % pairCount);
  const handleNext = () =>
    setCurrent((current + 1) % pairCount);

  return (
    <>
      {/* ===== Hero セクション ===== */}
      <section style={{ textAlign: 'center', padding: '4rem 0' }}>
        <h1>Image-guided 360-degree Scene Generation with Structural and Visual Consistency</h1>
        <p>
          Y. Katayama,&nbsp;R. Togo,&nbsp;K. Maeda,&nbsp;T. Ogawa, and &nbsp;M. Haseyama
        </p>
        <div>
          <a className="btn" href="#paper">Paper</a>
          <a className="btn" href="#arXiv">arXiv</a>
          <a className="btn" href="#code">Code</a>
        </div>
      </section>

      {/* ===== Abstract ===== */}
      <section id="abstract">
        <h2>Abstract</h2>
        <p>
              Scene generation is advancing rapidly, opening up new possibilities for virtual-world construction.
    This technology produces continuous 3D scenes and virtual environments from a single image along with textual descriptions.
    However, it remains challenging to maintain structural and visual consistency in text-driven scene generation, where sequential views are synthesized from a single input image.
    To address these inconsistencies, we propose a novel scene generation method based on (i) the use of multiple checkpoint images generated by a Native Multimodal Model (NMM), and (ii) rotation-aware frame interpolation.
    Assuming a fixed camera position with a 360-degree rotational view, we realize a scene generation that can preserve both structural and visual consistency across views.
    Experimental results demonstrate that our method achieves superior spatial-structural coherence and visual semantic consistency compared to existing approaches.
        </p>
      </section>

      {/* ===== Method ===== */}
      <section id="method">
        <h2>Method</h2>
        <img
          src={`${BASE}images/overview.svg`}
          alt="Method overview"
          style={{ width: '100%', margin: '1rem 0' }}
        />
        <p> coming soon...</p>
      </section>

      {/* ===== Comparison ===== */}
      <section id="comparison" style={{ position: 'relative' }}>
        <h2>Comparison with WonderJourney</h2>
        <button
          onClick={handlePrev}
          style={{
            position: 'absolute',
            left: '1rem',
            top: '50%',
            transform: 'translateY(-50%)'
          }}
          aria-label="Previous Example"
        >
          ◀
        </button>

        <VideoCompare
          otherSrc={videoPairs[current].otherSrc}
          oursSrc={videoPairs[current].oursSrc}
          otherLabel={videoPairs[current].otherLabel}
          oursLabel={videoPairs[current].oursLabel}
        />

        <button
          onClick={handleNext}
          style={{
            position: 'absolute',
            right: '1rem',
            top: '50%',
            transform: 'translateY(-50%)'
          }}
          aria-label="Next Example"
        >
          ▶
        </button>
      </section>

      {/* ===== More Examples ===== */}
      <section id="more_examples">
        <h2>More Examples</h2>
        <Gallery items={videoItems} />
      </section>

      {/* ===== BibTeX ===== */}
      <section id="bibtex">
        <h2>BibTeX</h2>
        coming soon...
        {/* <pre>{`@misc{asim2024metr3r,
  title={MEt3R: Measuring Multi-View Consistency in Generated Images},
  author={Asim, Mohammad and Wewer, Christopher and Wimmer, Thomas and Schiele, Bernt and Lenssen, Jan Eric},
  year={2024},
  howpublished={\\url{https://geometric-rl.mpi-inf.mpg.de/met3r/}}
}`}</pre> */}
      </section>
    </>
  );
};

export default Home;
